name: Build

on:
  pull_request:
    paths-ignore:
      - "Makefile"
      - '**.md'
      - 'docs/**'
    branches: [master]
  push:
    paths-ignore:
      - "Makefile"
      - '**.md'
      - 'docs/**'
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build